spring.application.name=Postres
spring.mvc.view.prefix=/WEB-INF/
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/postres_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=update
spring.mvc.hiddenmethod.filter.enabled=true
server.port=${PORT:8080}